POST https://linkbrary-api.vercel.app/9/auth/sign-up
Content-Type: application/json

{
  "email": "abcd@gmail.com",
  "password": "string",
  "name": "string"
}

###
POST https://linkbrary-api.vercel.app/9/auth/sign-in
Content-Type: application/json

{
  "email": "abcd@gmail.com",
  "password": "string"
  
}

###
POST https://linkbrary-api.vercel.app/9/folders
Content-Type: application/json

{
  "name": "1"
}